""" ""
Django settings for Learning project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

# TODO: Rotate Keys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# load_dotenv(".env.dev")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", False))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-16ky@(lc+@)f(d#*d(sxn9^lya=0$ko2&w%=(=bwsdnt+1m@g0"
)

ALLOWED_HOSTS = ["127.0.0.1", "nginx"]

# Application definition

INSTALLED_APPS = [
    "daphne",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.staticfiles",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.postgres",
    "Main",
    "Login",
    "Register",
    "Logout",
    "University",
    "User",
    "Dash",
    "Task",
    "Table",
    "Report",
    "Logs",
    "Card",
    "Mobile",
    "Change",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.gzip.GZipMiddleware",
]

ROOT_URLCONF = "Main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["Main/static/html"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Main.wsgi.application"
ASGI_APPLICATION = "Main.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": f"redis://:{os.environ.get('REDIS_PASSWORD', '1234')}@{os.environ.get('REDIS_HOST', 'localhost')}:6379/0",
                }
            ],
        },
    }
}

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("POSTGRES_DB", "smart"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "1234"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

REDIS = {
    "host": os.environ.get("REDIS_HOST", "localhost"),
    "port": 6379,
    "password": os.environ.get("REDIS_PASSWORD", "1234"),
}

CELERY_BROKER_URL = f"redis://:{os.environ.get('REDIS_PASSWORD', '1234')}@{os.environ.get('REDIS_HOST', 'localhost')}:6379/1"

CELERY_RESULT_BACKEND = f"redis://:{os.environ.get('REDIS_PASSWORD', '1234')}@{os.environ.get('REDIS_HOST', 'localhost')}:6379/1"

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 5 * 60

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 9,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "https://nginx:80",
    "https://127.0.0.1:81",
    "https://127.0.0.1:80",
]

CSRF_TRUSTED_ORIGINS = [
    "https://nginx:80",
    "https://127.0.0.1:81",
    "https://127.0.0.1:80",
]


CORS_ALLOW_HEADERS = [
    *default_headers,
    "Authorization",
    "Refresh",
    "request-origin",
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = "en-us"

USE_I18N = True

USE_TZ = False
TIME_ZONE = "Asia/Kolkata"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = os.path.join(
    BASE_DIR,
    "media",
)  # Directory for storing media files

MEDIA_URL = os.environ.get(
    "MEDIA_URL", "media/"
)  # URL prefix for accessing media files

APP_LOG = Path(BASE_DIR, "log", "app_log")
DATA_LOG = Path(BASE_DIR, "log", "data_log")
SMTP_LOG = Path(BASE_DIR, "log", "smtp_log")

LOGIN_URL = "Login:index"
WRITE_REGISTRY = os.environ.get("WRITE_REGISTRY", "writeExe://")
READ_REGISTRY = os.environ.get("READ_REGISTRY", "readExe://")
CREATE_REGISTRY = os.environ.get("CREATE_REGISTRY", "createExe://")

AES_KEY_1 = os.environ.get("AES_KEY_1", "5XpBavCf2rB0g4QD").encode()
AES_KEY_2 = os.environ.get("AES_KEY_2", "dpI56CKiEN8R0Lcx").encode()
DECRYPTION_KEY = os.environ.get("KEY", "123456789123456789123456").encode()

JWT_SECRET = os.environ.get("JWT_SECRET", "manvtv88gtmc2yg87ticeyvm4e2f1viu")
JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM", "HS256")
JWT_EXP_DELTA_MINUTES = 30
REFRESH_EXP_DELTA_MINUTES = 360

CERTIFICATE_EXPIRE_DAYS = 30
CARD_TOKEN_EXPIRE_MINUTES = 30

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True

ACCESS_PDF = os.environ.get("ACCESS_PDF", "3RvdpstRTj0HZWBvpFzF0fDScBjLFKzX")


class settingsInterface:
    MEDIA_ROOT = MEDIA_ROOT
    MEDIA_URL = MEDIA_URL
    APP_LOG = APP_LOG
    DATA_LOG = DATA_LOG
    SMTP_LOG = SMTP_LOG

    LOGIN_URL = LOGIN_URL

    WRITE_REGISTRY = WRITE_REGISTRY
    READ_REGISTRY = READ_REGISTRY
    CREATE_REGISTRY = CREATE_REGISTRY

    AES_KEY_1 = AES_KEY_1
    AES_KEY_2 = AES_KEY_2
    DECRYPTION_KEY = DECRYPTION_KEY
    REDIS = REDIS
    EMAIL_HOST_USER = EMAIL_HOST_USER
    DEFAULT_FROM_EMAIL = DEFAULT_FROM_EMAIL

    JWT_SECRET = JWT_SECRET
    JWT_ALGORITHM = JWT_ALGORITHM
    JWT_EXP_DELTA_MINUTES = JWT_EXP_DELTA_MINUTES
    REFRESH_EXP_DELTA_MINUTES = REFRESH_EXP_DELTA_MINUTES

    CERTIFICATE_EXPIRE_DAYS = CERTIFICATE_EXPIRE_DAYS
    CARD_TOKEN_EXPIRE_MINUTES = CARD_TOKEN_EXPIRE_MINUTES

    ACCESS_PDF = ACCESS_PDF
