# Generated by Django 5.0.7 on 2024-12-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftTiming',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
