# Generated by Django 5.0.7 on 2024-12-21 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTable',
            fields=[
                ('mongo_id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Mongo Object ID')),
                ('_no_of_rows', models.IntegerField(default=0, verbose_name='No of Rows in data')),
                ('verify_1_status', models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Rejected'), (None, 'Unchecked')], default=None, max_length=12, null=True, verbose_name='Verify Guy 1 status')),
                ('verify_assign_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verify Assignment 1')),
                ('verify_2_status', models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Rejected'), (None, 'Unchecked')], default=None, max_length=12, null=True, verbose_name='Verify Guy 2 status')),
                ('verify_assign_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verify Assignment 2')),
                ('verify_3_status', models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Rejected'), (None, 'Unchecked')], default=None, max_length=12, null=True, verbose_name='Verify Guy 3 status')),
                ('verify_assign_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verify Assignment 3')),
                ('belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs', to=settings.AUTH_USER_MODEL, verbose_name='Belongs to ')),
                ('verify_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_1', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 1')),
                ('verify_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_2', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 2')),
                ('verify_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_3', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 3')),
            ],
        ),
    ]
