# Generated by Django 5.0.7 on 2024-12-17 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(max_length=24, verbose_name='Mongo Object ID')),
                ('verify_1_done', models.BooleanField(default=False, verbose_name='Verify Guy 1 done')),
                ('verify_2_done', models.BooleanField(default=False, verbose_name='Verify Guy 2 done')),
                ('verify_3_done', models.BooleanField(default=False, verbose_name='Verify Guy 3 done')),
                ('belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs', to=settings.AUTH_USER_MODEL, verbose_name='Belongs to ')),
                ('verify_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_1', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 1')),
                ('verify_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_2', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 2')),
                ('verify_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_3', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 3')),
            ],
        ),
    ]
