# Generated by Django 5.0.7 on 2024-12-17 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_1', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 1'),
        ),
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_2', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 2'),
        ),
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_3', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 3'),
        ),
    ]
