# Generated by Django 5.0.7 on 2024-12-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtable',
            name='_no_of_rows',
        ),
        migrations.AddField(
            model_name='verificationtable',
            name='no_of_rows',
            field=models.IntegerField(default=0, verbose_name='No of Rows in data'),
        ),
    ]
