# Generated by Django 5.0.7 on 2024-12-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel', '0002_alter_verificationtable_verify_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtable',
            name='id',
        ),
        migrations.AlterField(
            model_name='verificationtable',
            name='mongo_id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Mongo Object ID'),
        ),
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_1_done',
            field=models.CharField(choices=[('Done', True), ('False', False)], default=False, max_length=12, verbose_name='Verify Guy 1 done'),
        ),
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_2_done',
            field=models.CharField(choices=[('Done', True), ('False', False)], default=False, max_length=12, verbose_name='Verify Guy 1 done'),
        ),
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_3_done',
            field=models.CharField(choices=[('Done', True), ('False', False)], default=False, max_length=12, verbose_name='Verify Guy 1 done'),
        ),
    ]
