# Generated by Django 5.0.7 on 2024-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel', '0003_remove_verificationtable_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_1_done',
            field=models.CharField(choices=[(True, 'Verify'), (False, 'Rejected'), (None, 'Unchecked')], default=False, max_length=12, verbose_name='Verify Guy 1 done'),
        ),
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_2_done',
            field=models.CharField(choices=[(True, 'Verify'), (False, 'Rejected'), (None, 'Unchecked')], default=False, max_length=12, verbose_name='Verify Guy 2 done'),
        ),
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_3_done',
            field=models.CharField(choices=[(True, 'Verify'), (False, 'Rejected'), (None, 'Unchecked')], default=False, max_length=12, verbose_name='Verify Guy 3 done'),
        ),
    ]
