# Generated by Django 5.0.7 on 2024-12-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Excel', '0008_alter_verificationtable_verify_1_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtable',
            name='verify_1',
        ),
        migrations.RemoveField(
            model_name='verificationtable',
            name='verify_1_done',
        ),
        migrations.RemoveField(
            model_name='verificationtable',
            name='verify_2',
        ),
        migrations.RemoveField(
            model_name='verificationtable',
            name='verify_2_done',
        ),
        migrations.RemoveField(
            model_name='verificationtable',
            name='verify_3',
        ),
        migrations.RemoveField(
            model_name='verificationtable',
            name='verify_3_done',
        ),
    ]
