# Generated by Django 5.0.7 on 2024-12-18 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel', '0009_remove_verificationtable_verify_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtable',
            name='verify_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_1', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 1'),
        ),
        migrations.AddField(
            model_name='verificationtable',
            name='verify_1_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Rejected'), (None, 'Unchecked')], default=None, max_length=12, null=True, verbose_name='Verify Guy 1 done'),
        ),
        migrations.AddField(
            model_name='verificationtable',
            name='verify_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_2', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 2'),
        ),
        migrations.AddField(
            model_name='verificationtable',
            name='verify_2_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Rejected'), (None, 'Unchecked')], default=None, max_length=12, null=True, verbose_name='Verify Guy 2 done'),
        ),
        migrations.AddField(
            model_name='verificationtable',
            name='verify_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Verify_3', to=settings.AUTH_USER_MODEL, verbose_name='Verify Guy 3'),
        ),
        migrations.AddField(
            model_name='verificationtable',
            name='verify_3_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Rejected'), (None, 'Unchecked')], default=None, max_length=12, null=True, verbose_name='Verify Guy 3 done'),
        ),
    ]
