# Generated by Django 5.0.7 on 2024-12-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel', '0010_verificationtable_verify_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_1_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Rejected'), (None, 'Unchecked')], default=None, max_length=12, null=True, verbose_name='Verify Guy 1 status'),
        ),
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_2_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Rejected'), (None, 'Unchecked')], default=None, max_length=12, null=True, verbose_name='Verify Guy 2 status'),
        ),
        migrations.AlterField(
            model_name='verificationtable',
            name='verify_3_status',
            field=models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Rejected'), (None, 'Unchecked')], default=None, max_length=12, null=True, verbose_name='Verify Guy 3 status'),
        ),
    ]
